### ISSUE TITLE
How do I build a static library for Windows?

### ISSUE THREAD

**Issue by eyalgolan1337** [libyal/libcerror#11] opened 2024-05-01 08:21 UTC
Hey, it is unclear from the documentation what would be the preferred way to build this library as a static library (.lib) on Windows.
Using the msvcpp converter python script doesn't create such targets.
Would it be possible to add an official way to build a static library on Windows - like the already existing Linux way.

Thanks!

**Comment by joachimmetz** [comment] 2024-05-01 08:24
> Would it be possible to add an official way to build a static library on Windows - like the already existing Linux way.

Are you asking about doing this on Windows (since you can do this with configure for cygwin / mingw) or are you specifically asking about msvcpp ?

**Comment by joachimmetz** [comment] 2024-05-01 09:45
Assuming duplicate of https://github.com/libyal/libyal/issues/97

**Closed by joachimmetz** 2024-05-01 09:45 UTC
Labels: question

**Comment by joachimmetz** [comment] 2024-05-01 10:17
> I think this should be added as an option in the default configuration

default configuration of what? libcerror supports it you just have to make sure you build is configured in the right way, configure (autotools) does this for you, unclear to me if either vcpkg or msvscpp does so?

**Comment by joachimmetz** [comment] 2024-05-01 11:19
> Then I think the question is how do you do this with msvscpp?

I recommend to have a closer look at the libcdatetime msvscpp files. It provides a static library configuration for msvscpp.
